FROM node:10-alpine

WORKDIR /app

# docker build . -t docker-node-image

# docker run --name docker-container -it docker-node-image sh

# docker images
# docker image prune -a

# docker container ls -a
# docker container stop <container name>
# docker container prune