version: "3"
services:
  nodedev:
    container_name: webpack_debugging
    build: ./docker/
    command: sh
    volumes:
      - .:/app
    working_dir: '/app'
    command: ['/bin/sh', '-c', 'tail -f /dev/null']
    ports:
      - 8000:8000
    environment:
      - CHOKIDAR_USEPOLLING=1
    restart: always
